"""init

Revision ID: 0005
Revises: 0004
Create Date: 2026-01-23 17:54:06.399991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('routes_owner_name_fkey'), 'routes', type_='foreignkey')
    op.drop_column('routes', 'owner_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('owner_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('routes_owner_name_fkey'), 'routes', 'users', ['owner_name'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###
