"""made tables in waypoint

Revision ID: 0006
Revises: 0005
Create Date: 2026-02-10 13:03:33.771114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_index(op.f('idx_waypoint_route_order'), table_name='waypoints')
    op.drop_column('waypoints', 'created_at')
    op.drop_column('waypoints', 'name')
    op.drop_column('waypoints', 'order_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('waypoints', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('waypoints', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_waypoint_route_order'), 'waypoints', ['route_id', 'order_index'], unique=False)
    op.drop_column('waypoints', 'title')
    # ### end Alembic commands ###
