"""changed comments relation

Revision ID: 0011
Revises: 0010
Create Date: 2026-03-05 12:07:18.207528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_id', sa.String(length=128), nullable=False))
    op.add_column('comments', sa.Column('waypoint_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('comments_owner_name_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'waypoints', ['waypoint_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['owner_id'], ['username'], ondelete='CASCADE')
    op.drop_column('comments', 'owner_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_owner_name_fkey'), 'comments', 'users', ['owner_name'], ['username'], ondelete='CASCADE')
    op.drop_column('comments', 'waypoint_id')
    op.drop_column('comments', 'owner_id')
    # ### end Alembic commands ###
