"""init

Revision ID: 0015
Revises: 0014
Create Date: 2026-03-07 13:56:52.951670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('route_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('comments_waypoint_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'waypoint_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('waypoint_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_waypoint_id_fkey'), 'comments', 'waypoints', ['waypoint_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'route_id')
    # ### end Alembic commands ###
